# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Administrator/Desktop/532proj1/part3/proj/proj_p3.srcs/sources_1/bd/design_1/ip/design_1_mask_axi532_0_1/design_1_mask_axi532_0_1.xci
# IP: The module: 'design_1_mask_axi532_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/532proj1/part3/proj/proj_p3.srcs/sources_1/Users/Administrator/Desktop/532proj1/part2/proj/proj_p2.srcs/constrs_1/new/cons1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mask_axi532_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Administrator/Desktop/532proj1/part3/proj/proj_p3.srcs/sources_1/bd/design_1/ip/design_1_mask_axi532_0_1/design_1_mask_axi532_0_1.xci
# IP: The module: 'design_1_mask_axi532_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/532proj1/part3/proj/proj_p3.srcs/sources_1/Users/Administrator/Desktop/532proj1/part2/proj/proj_p2.srcs/constrs_1/new/cons1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mask_axi532_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
