set_property PACKAGE_PIN R4 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN E22 [get_ports {in_data[0]}]
set_property PACKAGE_PIN F21 [get_ports {in_data[1]}]
set_property PACKAGE_PIN G21 [get_ports {in_data[2]}]
set_property PACKAGE_PIN G22 [get_ports {in_data[3]}]
set_property PACKAGE_PIN T14 [get_ports {out_largest[0]}]
set_property PACKAGE_PIN T15 [get_ports {out_largest[1]}]
set_property PACKAGE_PIN T16 [get_ports {out_largest[2]}]
set_property PACKAGE_PIN U16 [get_ports {out_largest[3]}]

set_property PACKAGE_PIN G4 [get_ports reset]
set_property PACKAGE_PIN H17 [get_ports in_valid]
set_property IOSTANDARD LVCMOS33 [get_ports in_valid]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {in_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_largest[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_largest[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_largest[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_largest[0]}]





set_property MARK_DEBUG true [get_nets {myPart1/D[0]}]
set_property MARK_DEBUG true [get_nets {myPart1/D[1]}]
set_property MARK_DEBUG true [get_nets {myPart1/D[2]}]
set_property MARK_DEBUG true [get_nets {myPart1/D[3]}]
set_property MARK_DEBUG true [get_nets {myPart1/out_value[0]}]
set_property MARK_DEBUG true [get_nets {myPart1/out_value[1]}]
set_property MARK_DEBUG true [get_nets {myPart1/out_value[2]}]
set_property MARK_DEBUG true [get_nets {myPart1/out_value[3]}]
set_property MARK_DEBUG true [get_nets {myPart1/Q[0]}]
set_property MARK_DEBUG true [get_nets {myPart1/Q[1]}]
set_property MARK_DEBUG true [get_nets {myPart1/Q[2]}]
set_property MARK_DEBUG true [get_nets {myPart1/Q[3]}]
set_property MARK_DEBUG true [get_nets myPart1/in_valid_IBUF]
set_property MARK_DEBUG true [get_nets myPart1/reset_IBUF]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {myPart1/Q[0]} {myPart1/Q[1]} {myPart1/Q[2]} {myPart1/Q[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {myPart1/out_value[0]} {myPart1/out_value[1]} {myPart1/out_value[2]} {myPart1/out_value[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {myPart1/D[0]} {myPart1/D[1]} {myPart1/D[2]} {myPart1/D[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list myPart1/in_valid_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list myPart1/reset_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
