# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/owner/ECE532/_archive_proj5_update2.xpr/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1.xci
# IP: The module: 'lwip_server_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/owner/ECE532/_archive_proj5_update2.xpr/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lwip_server_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/owner/ECE532/_archive_proj5_update2.xpr/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lwip_server_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/owner/ECE532/_archive_proj5_update2.xpr/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'lwip_server_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/owner/ECE532/_archive_proj5_update2.xpr/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1.xci
# IP: The module: 'lwip_server_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/owner/ECE532/_archive_proj5_update2.xpr/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lwip_server_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/owner/ECE532/_archive_proj5_update2.xpr/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lwip_server_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/owner/ECE532/_archive_proj5_update2.xpr/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'lwip_server_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
