# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/10695/Desktop/proj5/proj5.cache/wt [current_project]
set_property parent.project_path C:/Users/10695/Desktop/proj5/proj5.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/10695/Desktop/proj5/proj5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/hdl/lwip_server_wrapper.v
add_files C:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/lwip_server.bd
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_microblaze_0_0/lwip_server_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_microblaze_0_0/lwip_server_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_microblaze_0_0/lwip_server_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_dlmb_v10_0/lwip_server_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_dlmb_v10_0/lwip_server_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_ilmb_v10_0/lwip_server_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_ilmb_v10_0/lwip_server_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_dlmb_bram_if_cntlr_0/lwip_server_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_ilmb_bram_if_cntlr_0/lwip_server_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_lmb_bram_0/lwip_server_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_xbar_0/lwip_server_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_microblaze_0_axi_intc_0/lwip_server_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_microblaze_0_axi_intc_0/lwip_server_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_microblaze_0_axi_intc_0/lwip_server_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_mdm_1_0/lwip_server_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_mdm_1_0/lwip_server_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_clk_wiz_1_0/lwip_server_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_clk_wiz_1_0/lwip_server_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_clk_wiz_1_0/lwip_server_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_rst_clk_wiz_1_100M_0/lwip_server_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_rst_clk_wiz_1_100M_0/lwip_server_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_rst_clk_wiz_1_100M_0/lwip_server_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_timer_0_0/lwip_server_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_timer_0_0/lwip_server_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/lwip_server_axi_ethernet_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/synth/lwip_server_axi_ethernet_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_0/bd_98b9_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_98b9_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_0/bd_98b9_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_98b9_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_98b9_mac_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_98b9_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_98b9_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_2/bd_98b9_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_3/bd_98b9_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/bd_98b9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_uartlite_0_1/lwip_server_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_uartlite_0_1/lwip_server_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_uartlite_0_1/lwip_server_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_mig_7series_0_1/lwip_server_mig_7series_0_1/user_design/constraints/lwip_server_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_mig_7series_0_1/lwip_server_mig_7series_0_1/user_design/constraints/lwip_server_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_mig_7series_0_1/lwip_server_mig_7series_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_dma_0/lwip_server_axi_ethernet_0_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_dma_0/lwip_server_axi_ethernet_0_dma_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_dma_0/lwip_server_axi_ethernet_0_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_1/bd_5095_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_1/bd_5095_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_2/bd_5095_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_2/bd_5095_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_3/bd_5095_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_3/bd_5095_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_4/bd_5095_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_5/bd_5095_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_6/bd_5095_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_7/bd_5095_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_8/bd_5095_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_12/bd_5095_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_13/bd_5095_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_14/bd_5095_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_15/bd_5095_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_16/bd_5095_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_17/bd_5095_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_21/bd_5095_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_22/bd_5095_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_23/bd_5095_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_27/bd_5095_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_28/bd_5095_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_29/bd_5095_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_30/bd_5095_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_31/bd_5095_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_32/bd_5095_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_36/bd_5095_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_37/bd_5095_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_38/bd_5095_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_42/bd_5095_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_43/bd_5095_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_44/bd_5095_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_45/bd_5095_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_46/bd_5095_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_47/bd_5095_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_48/bd_5095_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_49/bd_5095_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_50/bd_5095_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_smc_0/bd_0/ip/ip_51/bd_5095_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_rst_mig_7series_0_100M_0/lwip_server_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_rst_mig_7series_0_100M_0/lwip_server_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_rst_mig_7series_0_100M_0/lwip_server_rst_mig_7series_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_1_0/lwip_server_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_1_0/lwip_server_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_1_0/lwip_server_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_2_0/lwip_server_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_2_0/lwip_server_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_gpio_2_0/lwip_server_axi_gpio_2_0.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_ila_0_0/lwip_server_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/10695/Desktop/proj5/proj5.srcs/sources_1/bd/lwip_server/lwip_server_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/10695/Desktop/proj5/proj5.srcs/constrs_1/new/proj_demo.xdc
set_property used_in_implementation false [get_files C:/Users/10695/Desktop/proj5/proj5.srcs/constrs_1/new/proj_demo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top lwip_server_wrapper -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lwip_server_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file lwip_server_wrapper_utilization_synth.rpt -pb lwip_server_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
