set_property PACKAGE_PIN T14 [get_ports {led_8b_tri_o[0]}]
set_property PACKAGE_PIN T15 [get_ports {led_8b_tri_o[1]}]
set_property PACKAGE_PIN T16 [get_ports {led_8b_tri_o[2]}]
set_property PACKAGE_PIN U16 [get_ports {led_8b_tri_o[3]}]
set_property PACKAGE_PIN V15 [get_ports {led_8b_tri_o[4]}]
set_property PACKAGE_PIN W16 [get_ports {led_8b_tri_o[5]}]
set_property PACKAGE_PIN W15 [get_ports {led_8b_tri_o[6]}]
set_property PACKAGE_PIN Y13 [get_ports {led_8b_tri_o[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_8b_tri_o[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_8b_tri_o[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_8b_tri_o[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_8b_tri_o[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_8b_tri_o[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_8b_tri_o[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_8b_tri_o[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_8b_tri_o[0]}]
set_property PACKAGE_PIN B22 [get_ports {but_5b_tri_i[0]}]
set_property PACKAGE_PIN F15 [get_ports {but_5b_tri_i[1]}]
set_property PACKAGE_PIN C22 [get_ports {but_5b_tri_i[2]}]
set_property PACKAGE_PIN D14 [get_ports {but_5b_tri_i[3]}]
set_property PACKAGE_PIN D22 [get_ports {but_5b_tri_i[4]}]

set_property IOSTANDARD LVCMOS12 [get_ports {but_5b_tri_i[4]}]
set_property IOSTANDARD LVCMOS12 [get_ports {but_5b_tri_i[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {but_5b_tri_i[2]}]
set_property IOSTANDARD LVCMOS12 [get_ports {but_5b_tri_i[1]}]
set_property IOSTANDARD LVCMOS12 [get_ports {but_5b_tri_i[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {sw_8b_tri_i[7]}]
set_property IOSTANDARD LVCMOS12 [get_ports {sw_8b_tri_i[6]}]
set_property IOSTANDARD LVCMOS12 [get_ports {sw_8b_tri_i[5]}]
set_property IOSTANDARD LVCMOS12 [get_ports {sw_8b_tri_i[4]}]
set_property IOSTANDARD LVCMOS12 [get_ports {sw_8b_tri_i[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {sw_8b_tri_i[2]}]
set_property IOSTANDARD LVCMOS12 [get_ports {sw_8b_tri_i[1]}]
set_property IOSTANDARD LVCMOS12 [get_ports {sw_8b_tri_i[0]}]
set_property PACKAGE_PIN E22 [get_ports {sw_8b_tri_i[0]}]
set_property PACKAGE_PIN F21 [get_ports {sw_8b_tri_i[1]}]
set_property PACKAGE_PIN G21 [get_ports {sw_8b_tri_i[2]}]
set_property PACKAGE_PIN G22 [get_ports {sw_8b_tri_i[3]}]
set_property PACKAGE_PIN H17 [get_ports {sw_8b_tri_i[4]}]
set_property PACKAGE_PIN J16 [get_ports {sw_8b_tri_i[5]}]
set_property PACKAGE_PIN K13 [get_ports {sw_8b_tri_i[6]}]
set_property PACKAGE_PIN M17 [get_ports {sw_8b_tri_i[7]}]

set_property IOSTANDARD LVCMOS25 [get_ports eth_mdio_mdc_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports eth_mdio_mdc_mdio_io]
set_property IOSTANDARD LVCMOS25 [get_ports {eth_rgmii_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {eth_rgmii_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {eth_rgmii_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {eth_rgmii_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {eth_rgmii_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {eth_rgmii_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {eth_rgmii_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {eth_rgmii_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports eth_rgmii_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports eth_rgmii_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports eth_rgmii_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports eth_rgmii_txc]

set_property MARK_DEBUG true [get_nets {lwip_server_i/but_5b_tri_i[1]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/sw_8b_tri_i[3]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/sw_8b_tri_i[4]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/sw_8b_tri_i[5]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/led_8b_tri_o[0]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/led_8b_tri_o[1]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/led_8b_tri_o[3]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/led_8b_tri_o[4]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/but_5b_tri_i[3]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/sw_8b_tri_i[2]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/sw_8b_tri_i[6]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/led_8b_tri_o[6]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/led_8b_tri_o[7]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/but_5b_tri_i[0]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/but_5b_tri_i[2]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/sw_8b_tri_i[1]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/led_8b_tri_o[2]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/led_8b_tri_o[5]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/sw_8b_tri_i[0]}]
set_property MARK_DEBUG true [get_nets {lwip_server_i/sw_8b_tri_i[7]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list lwip_server_i/clk_wiz_1/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {lwip_server_i/sw_8b_tri_i[0]} {lwip_server_i/sw_8b_tri_i[1]} {lwip_server_i/sw_8b_tri_i[2]} {lwip_server_i/sw_8b_tri_i[3]} {lwip_server_i/sw_8b_tri_i[4]} {lwip_server_i/sw_8b_tri_i[5]} {lwip_server_i/sw_8b_tri_i[6]} {lwip_server_i/sw_8b_tri_i[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {lwip_server_i/led_8b_tri_o[0]} {lwip_server_i/led_8b_tri_o[1]} {lwip_server_i/led_8b_tri_o[2]} {lwip_server_i/led_8b_tri_o[3]} {lwip_server_i/led_8b_tri_o[4]} {lwip_server_i/led_8b_tri_o[5]} {lwip_server_i/led_8b_tri_o[6]} {lwip_server_i/led_8b_tri_o[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {lwip_server_i/but_5b_tri_i[0]} {lwip_server_i/but_5b_tri_i[1]} {lwip_server_i/but_5b_tri_i[2]} {lwip_server_i/but_5b_tri_i[3]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
