# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/lwip_server_axi_ethernet_0_0.xci
# IP: The module: 'lwip_server_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/bd_98b9.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9 || ORIG_REF_NAME==bd_98b9} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_0/bd_98b9_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_eth_buf_0 || ORIG_REF_NAME==bd_98b9_eth_buf_0} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_1/bd_98b9_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_mac_0 || ORIG_REF_NAME==bd_98b9_mac_0} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_2/bd_98b9_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_c_shift_ram_0_0 || ORIG_REF_NAME==bd_98b9_c_shift_ram_0_0} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_3/bd_98b9_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_c_counter_binary_0_0 || ORIG_REF_NAME==bd_98b9_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_4/bd_98b9_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_xlconstant_0_0 || ORIG_REF_NAME==bd_98b9_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_5/bd_98b9_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_util_vector_logic_0_0 || ORIG_REF_NAME==bd_98b9_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/bd_98b9_ooc.xdc

# XDC: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/lwip_server_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lwip_server_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/synth/lwip_server_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lwip_server_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/lwip_server_axi_ethernet_0_0.xci
# IP: The module: 'lwip_server_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/bd_98b9.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9 || ORIG_REF_NAME==bd_98b9} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_0/bd_98b9_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_eth_buf_0 || ORIG_REF_NAME==bd_98b9_eth_buf_0} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_1/bd_98b9_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_mac_0 || ORIG_REF_NAME==bd_98b9_mac_0} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_2/bd_98b9_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_c_shift_ram_0_0 || ORIG_REF_NAME==bd_98b9_c_shift_ram_0_0} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_3/bd_98b9_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_c_counter_binary_0_0 || ORIG_REF_NAME==bd_98b9_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_4/bd_98b9_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_xlconstant_0_0 || ORIG_REF_NAME==bd_98b9_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/ip/ip_5/bd_98b9_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_98b9_util_vector_logic_0_0 || ORIG_REF_NAME==bd_98b9_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/bd_0/bd_98b9_ooc.xdc

# XDC: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/lwip_server_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lwip_server_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/owner/proj5/proj5.srcs/sources_1/bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/synth/lwip_server_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lwip_server_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
