# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/proj_demo.xdc

# Block Designs: bd/lwip_server/lwip_server.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server || ORIG_REF_NAME==lwip_server} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_microblaze_0_0/lwip_server_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_microblaze_0_0 || ORIG_REF_NAME==lwip_server_microblaze_0_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_dlmb_v10_0/lwip_server_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_dlmb_v10_0 || ORIG_REF_NAME==lwip_server_dlmb_v10_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_ilmb_v10_0/lwip_server_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_ilmb_v10_0 || ORIG_REF_NAME==lwip_server_ilmb_v10_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_dlmb_bram_if_cntlr_0/lwip_server_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==lwip_server_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_ilmb_bram_if_cntlr_0/lwip_server_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==lwip_server_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_lmb_bram_0/lwip_server_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_lmb_bram_0 || ORIG_REF_NAME==lwip_server_lmb_bram_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_xbar_0/lwip_server_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_xbar_0 || ORIG_REF_NAME==lwip_server_xbar_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_microblaze_0_axi_periph_0/lwip_server_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_microblaze_0_axi_periph_0 || ORIG_REF_NAME==lwip_server_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_microblaze_0_axi_intc_0/lwip_server_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_microblaze_0_axi_intc_0 || ORIG_REF_NAME==lwip_server_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_microblaze_0_xlconcat_0/lwip_server_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_microblaze_0_xlconcat_0 || ORIG_REF_NAME==lwip_server_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_mdm_1_0/lwip_server_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_mdm_1_0 || ORIG_REF_NAME==lwip_server_mdm_1_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_clk_wiz_1_0/lwip_server_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_clk_wiz_1_0 || ORIG_REF_NAME==lwip_server_clk_wiz_1_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_rst_clk_wiz_1_100M_0/lwip_server_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==lwip_server_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_axi_timer_0_0/lwip_server_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_axi_timer_0_0 || ORIG_REF_NAME==lwip_server_axi_timer_0_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_axi_ethernet_0_0/lwip_server_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_axi_ethernet_0_0 || ORIG_REF_NAME==lwip_server_axi_ethernet_0_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_axi_uartlite_0_1/lwip_server_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_axi_uartlite_0_1 || ORIG_REF_NAME==lwip_server_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_mig_7series_0_1/lwip_server_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_mig_7series_0_1 || ORIG_REF_NAME==lwip_server_mig_7series_0_1} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_axi_ethernet_0_dma_0/lwip_server_axi_ethernet_0_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_axi_ethernet_0_dma_0 || ORIG_REF_NAME==lwip_server_axi_ethernet_0_dma_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_axi_smc_0/lwip_server_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_axi_smc_0 || ORIG_REF_NAME==lwip_server_axi_smc_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_rst_mig_7series_0_100M_0/lwip_server_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==lwip_server_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_axi_gpio_0_1/lwip_server_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_axi_gpio_0_1 || ORIG_REF_NAME==lwip_server_axi_gpio_0_1} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_axi_gpio_1_0/lwip_server_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_axi_gpio_1_0 || ORIG_REF_NAME==lwip_server_axi_gpio_1_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_axi_gpio_2_0/lwip_server_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_axi_gpio_2_0 || ORIG_REF_NAME==lwip_server_axi_gpio_2_0} -quiet] -quiet

# IP: bd/lwip_server/ip/lwip_server_ila_0_0/lwip_server_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lwip_server_ila_0_0 || ORIG_REF_NAME==lwip_server_ila_0_0} -quiet] -quiet

# XDC: bd/lwip_server/lwip_server_ooc.xdc
